# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "test.TestData" do
    optional :param1, :double, 1
    optional :param2, :float, 2
    optional :param3, :int64, 3
    optional :param4, :uint64, 4
    optional :param5, :int32, 5
    optional :param6, :fixed64, 6
    optional :param7, :fixed32, 7
    optional :param8, :bool, 8
    optional :param9, :string, 9
    optional :param11, :message, 11, "test.TestSubData"
    optional :param12, :bytes, 12
    optional :param13, :uint32, 13
    optional :param14, :enum, 14, "test.TestEnum"
    optional :param15, :sfixed32, 15
    optional :param16, :sfixed64, 16
    optional :param17, :sint32, 17
    optional :param18, :sint64, 18
  end
  add_message "test.TestSubData" do
    optional :sub_param1, :int64, 1
    optional :sub_param2, :int64, 2
    optional :sub_param3, :int64, 3
    optional :sub_param4, :int64, 4
  end
  add_enum "test.TestEnum" do
    value :TEST_ENUM_NONE, 0
    value :TEST_ENUM_VAL_A, 1
    value :TEST_ENUM_VAL_B, 2
    value :TEST_ENUM_VAL_C, 3
    value :TEST_ENUM_VAL_D, 4
    value :TEST_ENUM_VAL_E, 5
  end
end

module Test
  TestData = Google::Protobuf::DescriptorPool.generated_pool.lookup("test.TestData").msgclass
  TestSubData = Google::Protobuf::DescriptorPool.generated_pool.lookup("test.TestSubData").msgclass
  TestEnum = Google::Protobuf::DescriptorPool.generated_pool.lookup("test.TestEnum").enummodule
end
